# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/suif4599/python_work/TransformerViz/gui/root.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(975, 859)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_model_menu = QtWidgets.QFrame(self.centralwidget)
        self.frame_model_menu.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_model_menu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_model_menu.setStyleSheet("QFrame {\n"
"    background-color: rgb(216, 216, 216)\n"
"}")
        self.frame_model_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_model_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_model_menu.setObjectName("frame_model_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_model_menu)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_model_menu)
        self.label.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"    font-size:18pt;\n"
"    border: 2px solid #606060;\n"
"    border-radius: 10px;\n"
"    padding: 3px;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.module_list = QtWidgets.QListView(self.frame_model_menu)
        self.module_list.setObjectName("module_list")
        self.verticalLayout_2.addWidget(self.module_list)
        self.horizontalLayout.addWidget(self.frame_model_menu)
        self.frame_content = QtWidgets.QFrame(self.centralwidget)
        self.frame_content.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_content.setStyleSheet("QFrame {\n"
"    background-color: rgb(255, 255, 255)\n"
"}")
        self.frame_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_content)
        self.verticalLayout.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_detail = QtWidgets.QFrame(self.frame_content)
        self.frame_detail.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_detail.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_detail.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_detail.setObjectName("frame_detail")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_detail)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_description = QtWidgets.QFrame(self.frame_detail)
        self.frame_description.setStyleSheet("QFrame {\n"
"    background-color: rgb(216, 216, 216)\n"
"}")
        self.frame_description.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_description.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_description.setObjectName("frame_description")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_description)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_description)
        self.label_2.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"    font-size:14pt;\n"
"    padding: 3px;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.text_description = QtWidgets.QTextBrowser(self.frame_description)
        self.text_description.setObjectName("text_description")
        self.verticalLayout_3.addWidget(self.text_description)
        self.horizontalLayout_2.addWidget(self.frame_description)
        self.frame_control = QtWidgets.QFrame(self.frame_detail)
        self.frame_control.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_control.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_control.setStyleSheet("QFrame {\n"
"    border: 3px;\n"
"    background-color: rgb(216, 216, 216);\n"
"}")
        self.frame_control.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_control.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_control.setObjectName("frame_control")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_control)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.frame_control)
        self.label_8.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"    font-size:14pt;\n"
"    padding: 3px;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.position_mode_frame = QtWidgets.QFrame(self.frame_control)
        self.position_mode_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.position_mode_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.position_mode_frame.setObjectName("position_mode_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.position_mode_frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.position_mode_frame)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.position_mode_option = QtWidgets.QComboBox(self.position_mode_frame)
        self.position_mode_option.setObjectName("position_mode_option")
        self.horizontalLayout_6.addWidget(self.position_mode_option)
        self.verticalLayout_5.addWidget(self.position_mode_frame)
        self.layer_mix_frame = QtWidgets.QFrame(self.frame_control)
        self.layer_mix_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.layer_mix_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.layer_mix_frame.setObjectName("layer_mix_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layer_mix_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layer_mix_frame)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.layer_mix_option = QtWidgets.QComboBox(self.layer_mix_frame)
        self.layer_mix_option.setObjectName("layer_mix_option")
        self.horizontalLayout_3.addWidget(self.layer_mix_option)
        self.verticalLayout_5.addWidget(self.layer_mix_frame)
        self.head_mix_frame = QtWidgets.QFrame(self.frame_control)
        self.head_mix_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.head_mix_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.head_mix_frame.setObjectName("head_mix_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.head_mix_frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.head_mix_frame)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.head_mix_option = QtWidgets.QComboBox(self.head_mix_frame)
        self.head_mix_option.setObjectName("head_mix_option")
        self.horizontalLayout_4.addWidget(self.head_mix_option)
        self.verticalLayout_5.addWidget(self.head_mix_frame)
        self.temperature_frame = QtWidgets.QFrame(self.frame_control)
        self.temperature_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.temperature_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.temperature_frame.setObjectName("temperature_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.temperature_frame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.temperature_frame)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.temperature_input = QtWidgets.QLineEdit(self.temperature_frame)
        self.temperature_input.setObjectName("temperature_input")
        self.horizontalLayout_7.addWidget(self.temperature_input)
        self.temperature_set_button = QtWidgets.QPushButton(self.temperature_frame)
        self.temperature_set_button.setObjectName("temperature_set_button")
        self.horizontalLayout_7.addWidget(self.temperature_set_button)
        self.verticalLayout_5.addWidget(self.temperature_frame)
        self.frame = QtWidgets.QFrame(self.frame_control)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.fontsize_input = QtWidgets.QLineEdit(self.frame)
        self.fontsize_input.setObjectName("fontsize_input")
        self.horizontalLayout_8.addWidget(self.fontsize_input)
        self.fontsize_set_button = QtWidgets.QPushButton(self.frame)
        self.fontsize_set_button.setObjectName("fontsize_set_button")
        self.horizontalLayout_8.addWidget(self.fontsize_set_button)
        self.verticalLayout_5.addWidget(self.frame)
        self.horizontalLayout_2.addWidget(self.frame_control)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addWidget(self.frame_detail)
        self.frame_input = QtWidgets.QFrame(self.frame_content)
        self.frame_input.setStyleSheet("QFrame {\n"
"    background-color: rgb(216, 216, 216)\n"
"}")
        self.frame_input.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_input.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_input.setObjectName("frame_input")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_input)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_input)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.text_input = QtWidgets.QLineEdit(self.frame_input)
        self.text_input.setObjectName("text_input")
        self.horizontalLayout_5.addWidget(self.text_input)
        self.confirm_button = QtWidgets.QPushButton(self.frame_input)
        self.confirm_button.setObjectName("confirm_button")
        self.horizontalLayout_5.addWidget(self.confirm_button)
        self.verticalLayout.addWidget(self.frame_input)
        self.frame_attention = QtWidgets.QFrame(self.frame_content)
        self.frame_attention.setStyleSheet("QFrame {\n"
"    background-color: rgb(216, 216, 216)\n"
"}")
        self.frame_attention.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_attention.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_attention.setObjectName("frame_attention")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_attention)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout.addWidget(self.frame_attention)
        self.verticalLayout.setStretch(0, 6)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 16)
        self.horizontalLayout.addWidget(self.frame_content)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 975, 20))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.actioncity = QtWidgets.QAction(MainWindow)
        self.actioncity.setObjectName("actioncity")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Modules"))
        self.label_2.setText(_translate("MainWindow", "Description"))
        self.label_8.setText(_translate("MainWindow", "Options"))
        self.label_6.setText(_translate("MainWindow", "AttentionPos: "))
        self.label_3.setText(_translate("MainWindow", "LayerMixMode:"))
        self.label_4.setText(_translate("MainWindow", "HeadMixMode:"))
        self.label_7.setText(_translate("MainWindow", "Temperature:"))
        self.temperature_set_button.setText(_translate("MainWindow", "Set"))
        self.label_9.setText(_translate("MainWindow", "Fontsize:"))
        self.fontsize_set_button.setText(_translate("MainWindow", "Set"))
        self.label_5.setText(_translate("MainWindow", "Input:"))
        self.confirm_button.setText(_translate("MainWindow", "Visualize"))
        self.actioncity.setText(_translate("MainWindow", "city"))
